title: Audiotarky
email: your-email@example.com
description: >-
  Audiotarky (Audio Autarky) is a new streaming platform, focussed on paying musicians directly & clearly for all the music they create.
baseurl: "/site"
url: "https://audiotarky.com"
twitter_username: audiotarky
github_username:  audiotarky
ilp: "$wm.vanilla.so/pay/e5a34e66-5b0e-408a-bdd2-89f483c54a1a"
permalink: /:slugified_categories/:title/index.html
exclude:
 - CNAME
 - makepost.py
 - venv
 - gen.sh
collections_dir: data
collections:
  artist:
    output: true
    sort_by: name
    permalink: /:title/index.html
  album:
    output: true
    permalink: /:slugified_categories/:title/index.html
  payid:
    output: true
    permalink: /:slug
  track:
    output: true
    sort_by: track_number
    permalink: /:slugified_categories/:title/index.html